<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <EnableDefaultItems>false</EnableDefaultItems>
    <DefineSilverlight>true</DefineSilverlight>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="UI\Units\ThemeSwitch.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenSilver" Version="3.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="Themes\Generic.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Themes\Units\ThemeSwitch.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

</Project>
